spring:
  datasource:
    url: jdbc:postgresql://db:5432/ticket_management  # PostgreSQL connection URL
    username: postgres  # PostgreSQL username
    password: postgres  # PostgreSQL password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the schema; can be 'create', 'validate', or 'none'
    show-sql: true  # Show SQL queries in the logs
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true  # Format JSON output for better readability

  mvc:
    cors:
      allowed-origins: http://localhost:4200,http://host.docker.internal:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

cors:
  allowed-origins: http://localhost:4200,http://localhost,http://host.docker.internal:4200

# Profile-specific configuration
logging:
  level:
    org:
      springframework: INFO
      hibernate: WARN
      liquibase: WARN


